### ISSUE TITLE
Missing launch script from docker containers

### ISSUE THREAD

**Issue by crisptrutski** [onyx-platform/onyx-template#13]
[The script file reference in the Dockerfile](https://github.com/onyx-platform/onyx-template/blob/master/resources/leiningen/new/onyx_app/Dockerfile#L16-L18) does not seem to be generated.

**Comment by MichaelDrogalis** [comment]
Fixed in b7f82f00218d44850a7b9a3f72054d7898a4fc17, released to Clojars. Thanks!
