### ISSUE TITLE
lein new should provide an argument to name the example job

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx-template#16]
It's fairly tedious to rename all the sample files to an appropriate job name

**Comment by gardnervickers** [comment]
Any ideas for how this should look? Currently we specify options like this,
`lein new onyx-app onyxapp -- +docker +metrics`

Maybe we could change that to 
`lein new onyx-app onyxapp -- +opts [docker metrics] +jobname <jobname>`

**Comment by MichaelDrogalis** [comment]
Could we make the jump to tools.cli so we can could do `--job-name` and get an automatic help screen?

**Comment by gardnervickers** [comment]
Yea, thats a good option too. It would be nice to do `onyx new job myjob` and have it create all the scaffolding. I am going to wait on this then.

**Comment by gardnervickers** [comment]
This issue is sort of moot now that we use task bundles
