### ISSUE TITLE
Need to add slf4j impl to deps

### ISSUE THREAD

**Issue by metasoarous** [onyx-platform/onyx-template#2]
Getting this when I run a fresh install:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder". 
```

and after that no logging. Adding `[org.slf4j/slf4j-simple "1.6.1"]`to deps solved the problem.

**Comment by MichaelDrogalis** [comment]
I added this to Onyx itself a few days ago, then backed it out. The amount of logging that ZooKeeper emits after adding the jar is _gigantic_. Can you figure out how to tone that down? If so, would be happy to accept the patch.

**Comment by metasoarous** [comment]
Ah gotcha; Yeah, I've always just lived with the ZooKeeper chatter in things like storm, but I can appreciate trying to leave that out. I didn't realize that's all slf4j was getting used for.

It looks like it might be possible to raise the log level for _only_ zookeeper stuffs: http://stackoverflow.com/questions/16738364/how-can-i-suppress-info-logs-in-an-hbase-client-application.

**Comment by MichaelDrogalis** [comment]
Gonna close this one. I tried adding this dependency to the core again using the set log level on the link, but was unsuccessful. If you can make it work, please send the same patch over to core. Thanks. :)
