### ISSUE TITLE
Adopt new development idioms

### ISSUE THREAD

**Issue by gardnervickers** [onyx-platform/onyx-template#21]
In light of the [new idioms for testing onyx jobs](https://github.com/onyx-platform/onyx/blob/develop/doc/user-guide/testing-onyx-jobs.md#automatic-resource-clean-up) posted, we should update the onyx-template to automatically generate these for `:dev` and `:prod` cases. 

There are 3 points so far. 
- [x] Automatic Resource Cleanup
  - [x] Use `with-test-env` macro to launch the test environment
- [x] Code Reloading
  - [x] This works currently. I don't foresee this being different.
- [x] In-Memory I/O
  - [x] Base Job idiom
    - [x] Workflows
    - [x] Catalog
    - [x] Lifecycles
    - [x] Flow Conditions
  - [x] `cond->` builder pattern idiom

**Comment by lbradstreet** [comment]
I'd also add:
- [ ] Include onyx-metrics in the default project, with timbre metrics enabled by default.

**Comment by gardnervickers** [comment]
#15 will be addressed by this as well. The System object will only be used (explicitly) for prod.
