### ISSUE TITLE
Docker script should probably run commands via daemon

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx-template#22]
Media driver and peers should probably run via the  daemon command. This is probably preferable to restarting to container, and even so, that would not restart the media driver.

It'd also be good if the standard tests could be run under a built docker container built via the template. This would provide a good test of the docker functionality. L

**Comment by gardnervickers** [comment]
Is this a command provided by docker? I cant seem to find this in the docs. Is this different from the `ENTRYPOINT` configuration?

**Comment by gardnervickers** [comment]
What do you think of switching the base image to use [Phusion](https://hub.docker.com/r/phusion/baseimage), and using that to keep the Aeron driver and the peer running?

**Comment by lbradstreet** [comment]
Phusion sounds good to me. Any idea how you can use it to keep two separate JVMs daemonised though?

**Comment by gardnervickers** [comment]
I was going to do what this person does. 
http://stackoverflow.com/a/33288867

**Comment by gardnervickers** [comment]
```
  PID TTY          TIME CMD
    1 ?        00:00:00 sh
   11 ?        00:00:22 java
   12 ?        00:00:13 java
  135 ?        00:00:00 ps
```

Looks like this is working correctly after bf3b30e. I will test more when I get home. I ended up just using the `/sbin/my_init` to run the aeron driver and onyx, logging out to `/var/log/`. I'm not sure how `my_init` handles crashes, need to read up on it more.
