### ISSUE TITLE
Use Kafka + postgres for the docker-compose example

### ISSUE THREAD

**Issue by gardnervickers** [onyx-platform/onyx-template#24]
It seems that the first step most people take with Onyx past core.async is getting a workflow involving Kafka. Now that we have a docker-compose file, we should either provide the option or default to a workflow with Kafka->postgres. 

Maybe we could do something with twitter, or some free datasource to load into Kafka, run a couple transforms and pipe to postgres.

**Comment by lbradstreet** [comment]
I like it. Over the long run it'd be cool to have the "from" and "to" be complete configurable and auto-generated. 

For now Kafka and something else (probably SQL) will go a long way.
