### ISSUE TITLE
Docker run failes due to mount error

### ISSUE THREAD

**Issue by bcambel** [onyx-platform/onyx-template#28]
`docker run -it bctest:0.1.0 /bin/bash`
returns the following error

```
+ mount -t tmpfs -o remount,rw,nosuid,nodev,noexec,relatime,size=256M tmpfs /dev/shm
mount: cannot remount block device tmpfs read-write, is write-protected
```

any idea how can I solve it ? 
Thanks

**Comment by bcambel** [comment]
alright, I realized, I missed the run-container script.

**Comment by lbradstreet** [comment]
Hi. I believe you need to start the container in privileged mode via --privileged. Unfortunately, this is necessary until docker has a shm-size parameter.

**Comment by bcambel** [comment]
thanks Lucas
