### ISSUE TITLE
Exception: aeron cnc file version not understood: version=3

### ISSUE THREAD

**Issue by tendant** [onyx-platform/onyx-template#32]
Looks like it is only happening with onyx 0.8.2. After changing onyx to 0.8.3, it works fine.

**Comment by MichaelDrogalis** [comment]
Hi @tendant. We upgraded Aeron between those two versions. Aeron changed an internal format between each of those versions, and throws an exception when it gets a mismatch. You can delete your Aeron dir if you want to hop around between versions.

**Comment by tendant** [comment]
@MichaelDrogalis thanks for explanation. 

I don't see the Aeron directory anywhere in the project. I am still running the dev environment. It works fine after restarting the repl. 

Just wondering will it be a problem in production after upgrading onyx to new version in future.

**Comment by MichaelDrogalis** [comment]
@tendant The stack trace generally says where the Aeron path is. On my Mac, it's under `/var` - not inside the Onyx project itself. You can try a `find` for Aeron files, too.

It should be fine for production. If you're going to do a hot upgrade, I'd recommend doing it in a rolling fashion. You can always check the changelog to see if we upgraded Aeron between versions. One of the advantages to running Onyx in Docker is that it will create a fresh Aeron directory every time.
