### ISSUE TITLE
Use lib-onyx for common utilities

### ISSUE THREAD

**Issue by gardnervickers** [onyx-platform/onyx-template#34]
Currently I have moved and tried to generalize catalog and lifecycle "instrumentation" functions for 
- [x] `core_async`
- [x] `kafka`
- [x] `logging`
- [x] `sql`
  - [x] provide SQL migration or at least ensure proper schema using [Joplin](https://github.com/juxt/joplin)
  - [x] refuse to start the task if the DB cannot be reached.

**Comment by gardnervickers** [comment]
I hesitate to drag in all of Joplin just for assuring DB schema. If anyone knows of a better way to do this (and still remain DB agnostic) I would gladly substitute that.

**Comment by MichaelDrogalis** [comment]
Ragtime?

**Comment by gardnervickers** [comment]
Going to track this in the lib-onyx repo, this is a larger undertaking that I originally assumed.
