### ISSUE TITLE
Provide better docs around the new idioms

### ISSUE THREAD

**Issue by gardnervickers** [onyx-platform/onyx-template#35]
We should be focusing on how to get the bare minimum case (docker-compose + meetup.com streaming) setup. Let's try to keep information about the utility functions contained in [lib-onyx](https://github.com/onyxplatform/onyx-template). We should provide docs around how to get a simple workflow running, but for things like reading from multiple Kafka topics or changing the DB schema we should instead provide links to the appropriate lib-onyx docs.

**Comment by gardnervickers** [comment]
- [x] The template will not start an onyx job for you. We need explicit instructions to do so. 
- [x] Sometimes docker inherits the wrong DNS host causing Kafkacat to crash. Document this???

**Comment by gardnervickers** [comment]
Both Emacs and Vim provide hotkeys to refresh the repl. We should make this easier for users not in either of those editors.

**Comment by lbradstreet** [comment]
vim doesn't provide a clojure.tools.namespace.repl/refresh one, though it's pretty easy to add. I'd suggest  just mentioning the terminal command, rather than a specific vim command. I guess I could mention how I do mine.
