### ISSUE TITLE
Provide an option in the aeron-media-driver launcher to delete the existing dirs

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx-template#37]
There may be incompatibilities between versions and these should be cleared. I'm not sure if they should be cleared by default as another media driver may still be running. My preference would be to provide a better warning on IllegalStateException thrown on startup, and then provide a command line arg to clear it via `(.dirsDeleteOnStart ctx)`.

**Comment by gardnervickers** [comment]
Would catching `IllegalStateException` and telling the user to clear their Aeron directory be sufficient until we have better cli tools?

**Comment by lbradstreet** [comment]
Done
