### ISSUE TITLE
ZooKeeper address should probably come from environ

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx-template#40]
See 
https://github.com/onyx-platform/onyx-template/blob/feature/new-idioms/src/leiningen/new/onyx_app/src/onyx_app/jobs/sample_submit_job.clj#L35
and 
https://github.com/onyx-platform/onyx-template/blob/feature/new-idioms/src/leiningen/new/onyx_app/src/onyx_app/jobs/sample_submit_job.clj#L43

Environ tends to have the best go-to prod story for that stuff, rather than placing it in the edn.

**Comment by lbradstreet** [comment]
I think edn for the different modes is good for most things other than addresses (including bind-addr). Potentially we could allow these to be set but overridden.

**Comment by gardnervickers** [comment]
Fixed this by using aero
