### ISSUE TITLE
Get rid of channel memoization

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx-template#41]
The tests in onyx core now just use atoms to hold the channels and this is a lot easier for new users to understand, while maintaining repl reloading e.g. https://github.com/onyx-platform/onyx/blob/0.8.x/test/onyx/peer/min_peers_test.clj#L65

@MichaelDrogalis, I think we agreed that we can rip it out of onyx-template, but I'd still like to check that we're on the same page.

**Comment by MichaelDrogalis** [comment]
@lbradstreet Yep, good to me.

**Comment by gardnervickers** [comment]
We can copy this into the template
https://github.com/onyx-platform/lib-onyx/blob/master/src/lib_onyx/plugins/core_async.clj
