### ISSUE TITLE
Update documentation to reflect new fn signature

### ISSUE THREAD

**Issue by lvh** [onyx-platform/onyx-template#46]
https://github.com/onyx-platform/onyx-template/blob/31f05ca5fed17cb1dcab3f307214bdeaaa1e866f/src/leiningen/new/onyx_app/README.md#production claims:

> Running onyx in production just requires building an uberjar and running the {{app-name}}.launcher.launch_prod_peers function with an onyx_id and a npeers argument.

... but that function no longer takes onyx_id.

**Comment by lvh** [comment]
Some other portions in that section looks like they could use updates as well.

**Comment by gardnervickers** [comment]
Thanks @lvh
