### ISSUE TITLE
runsv aeron: fatal: unable to start ./run: access denied

### ISSUE THREAD

**Issue by jackdempsey** [onyx-platform/onyx-template#48]
When running the docker-compose up command it looks like things are working until this starts flooding the screen. Any thoughts?

**Comment by gardnervickers** [comment]
Hey @jackdempsey, first thought would be to check to make sure you have the scripts in /scripts executable. 

If you'd like to jump on the Onyx gitter 
https://gitter.im/onyx-platform/onyx
or Slack Clojurians I can help diagnose this.

**Comment by jackdempsey** [comment]
hey gardner, that helped. No longer have that issue, just see this now:

```
te cxid:0x14 zxid:0xcf txntype:-1 reqpath:n/a Error Path:/onyx/1/job-scheduler/scheduler Error:KeeperErrorCode = NodeExists for /onyx/1/job-scheduler/scheduler
zookeeper_1 | 2016-02-18 16:48:43,454 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing sessionid:0x152f54856d70008 type:create cxid:0x15 zxid:0xd0 txntype:-1 reqpath:n/a Error Path:/onyx/1/messaging/messaging Error:KeeperErrorCode = NodeExists for /onyx/1/messaging/messaging
peer_1      | Attempting to connect to to Zookeeper:  zk:2181
peer_1      | Started peers. Blocking forever.
```

Stupid copy/paste with backticks included messed up mysql connect. All good now :-)
