### ISSUE TITLE
Version without docker?

### ISSUE THREAD

**Issue by hansgru** [onyx-platform/onyx-template#5]
Docker is very nice, and useful, but unfortunately there are many places where it can't be adopted yet.
Would be nice if the template would have a version without it.

**Comment by MichaelDrogalis** [comment]
You can simply delete the Dockerfile if you don't want to use it. At the moment, it's the primary way deploy, though. Perhaps in the future when the template is more "Rails-esque" we can parameterize the deployment strategy, but for now it's easy enough to remove the relevant files.

**Comment by hansgru** [comment]
but the shell scripts are using docker too.
