### ISSUE TITLE
Slim down docker image with Alpine Linux

### ISSUE THREAD

**Issue by gardnervickers** [onyx-platform/onyx-template#50]
The current docker image is almost a gigabyte in size. It's beginning to look like we're embracing docker pretty heavily so slimming down this image size would be a good idea.

https://developer.atlassian.com/blog/2015/08/minimal-java-docker-containers/
The Atlassian folks write about using Alpine Linux to get an image with Java that's ~ 360MB.

**Comment by neverfox** [comment]
Relevant: https://github.com/phusion/baseimage-docker/issues/275
