### ISSUE TITLE
shm_size can be set when running container

### ISSUE THREAD

**Issue by gardnervickers** [onyx-platform/onyx-template#53]
Since docker 1.10.x we can set the shm_size without being in privileged mode. We should prefer this over what we're currently doing in the media driver startup scripts.

**Comment by lbradstreet** [comment]
Yup, agreed. Note that this will break the docker-compose demo since it can't currently do it. That's why I didn't make this change when this option came out :(. I think we should still make it though.

**Comment by gardnervickers** [comment]
docker/compose#2823 It looks like it was merged in a couple weeks ago, hopefully it's out now/soon!

**Comment by lbradstreet** [comment]
Sweet!
