### ISSUE TITLE
Bare template

### ISSUE THREAD

**Issue by neverfox** [onyx-platform/onyx-template#58]
Is there any interest in allowing this template to produce a bare project, i.e. without the sample job? I think the sample is valuable, but it would be useful to have a good starting point for a new Onyx project that is completely fill-in-the-blanks, but would have all the suggested best practices covered as far as code organization, basic core dependencies, a test rig, and perhaps a "reloaded" workflow. We're probably going to build one to our needs internally, but I think it could be useful for the community plugin also.

**Comment by lbradstreet** [comment]
This is absolutely something we want to do, and we used to do, but we haven't had a chance to do it with the updated template yet.

**Comment by MichaelDrogalis** [comment]
A contribution here would be great if you get to it before we do.

**Comment by neverfox** [comment]
Definitely. I'm still playing around with my preferred organization scheme. There are a few different ways you all have approached it (`onyx-starter`, `engraver` and this all take slightly different approaches). Is there one in your mind that is working out to be the favorite in practice?

**Comment by MichaelDrogalis** [comment]
Using task bundles as this repository does is the way to go. cc @gardnervickers

**Comment by gardnervickers** [comment]
@neverfox I've been quite busy and have not gotten around to finishing off my template refresh. If you want to help here I can make some time to go over the task bundle changes. It would be very welcome!

**Comment by neverfox** [comment]
@gardnervickers What did you have in mind?

**Comment by gardnervickers** [comment]
@neverfox We have been working on "task bundles" which are composable functions that allow behavior to be captured in the form of plain old data transformations. An example of this is in the Kafka tests. 
https://github.com/onyx-platform/onyx-kafka/blob/0.9.x/test/onyx/plugin/input_test.clj#L32

As an added bonus, we decided to allow users to attach and extend schema as part of their task bundles. For example, if you're particular bundle of functionality requires the `:sql/db-uri` key set in the task-map, we wanted to make it possible for users to do that. There was a couple issues with the previous way we were doing it (and that is the way it's currently done in the plugins) but once onyx-platform/onyx#575 gets sorted out we'll have access to the desired functionality. 

We also have a (pretty barebones) [twitter plugin](https://github.com/onyx-platform/onyx-twitter) now, designed to replace the janky `meetup.com-> curl-> Kafka` setup that often breaks. 

But as far as the `bare` template goes, I was planning on having the Aeron media driver bootup code, the peer bootup code, aero config, an empty job and an accompanying test.

**Comment by gardnervickers** [comment]
Closing as we now provide this
