### ISSUE TITLE
Ensure Java opts are set somewhere for daemon run

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx-template#64]
Need MEDIA_DRIVER_JAVA_OPTS to run in -server mode, and peer with -server + G1GC. I don't know if the environment variables for these are set anywhere by default - though it's probably a job of the orchestration system that you're using, in which case it probably just needs to be documented better.

**Comment by gardnervickers** [comment]
Would it be sufficient to default them in the launch scripts if they are not explicitly set? Documentation around this does need to be improved.
