### ISSUE TITLE
config.edn should not default logging config to nil

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx-template#65]
This does not allow tests to run. See discussion:

Hi, I'm just trying out the new onyx lein template (I'm also an onyx noob in general) and I'm getting a failure when running `lein test`:

```
lein test :only try-onyx-template.jobs.basic-test/basic-test

ERROR in (basic-test) (core.clj:151)
Uncaught exception, not in assertion.
expected: nil
  actual: clojure.lang.ExceptionInfo: Value does not match schema: {:onyx.log/config (not (map? nil))}
 at schema.core$validator$fn__11050.invoke (core.clj:151)
    schema.core$validate.invokeStatic (core.clj:160)
```

Any ideas?

edit resources/config.edn

[5:45]  
 ```  :onyx.log/config #profile {:default nil
                             :docker {:level :info}}}

```
(edited)

agile_geek [5:49 PM]  
I changed that `:default` entry in two places in config.edn and it ran OK

agile_geek [5:49 PM]  
in `:env-config` and in `:peer-config`

```

**Comment by gardnervickers** [comment]
onyx-platform/onyx@8d2099320336e2319c39a2c05eecd906ee06d139 restricts this.
How should be be switching between using the standard file logger (`nil`) and the stdout logger `{:level :info}`?

**Comment by lbradstreet** [comment]
We could use three different solutions:

Loosen up the schema and check that onyx still defaults correctly when nil (it should).

Replicate the whole default onyx logging config in the config.edn. 

Have the logging key only be present in the config if the value is present. I don't think aero has a good way to do this.

Of these three I think #1 is the best bet.
