### ISSUE TITLE
Dockerfile is outdated

### ISSUE THREAD

**Issue by danielstockton** [onyx-platform/onyx-template#72]
The Dockerfile doesn't work with later versions of docker, since the ADD directive automatically extracts recognized extensions like tar.gz.

It can be fixed with something like:

```
ADD https://github.com/just-containers/s6-overlay/releases/download/v1.11.0.1/s6-overlay-amd64.tar.gz /tmp/

RUN cp -r /tmp/etc/* /etc
RUN cp -r /tmp/usr/* /usr
RUN mv /tmp/init /
```

**Comment by lbradstreet** [comment]
Hi @danielstockton, thanks for the report!

@gardnervickers could you please review this issue when you get a chance?

**Comment by gardnervickers** [comment]
@lbradstreet @danielstockton Good opportunity to switch to #69 and use an Aeron sidecar container. Thank you I'll try and make some time for this.

**Comment by lbradstreet** [comment]
Pushed @danielstockton's suggested fix for this to onyx-template. @gardnervickers will solve #69 later. Thanks!
